spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: Wzj961127.


initialization:
  file:
    users: users.json
    roles: roles.json
    permissions: permissions.json
